permalink: /:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Haowu Ge
  email: ghw@7axu.com
  link: http://bookcase.gehaowu.eu.org
  weibo: http://weibo.com/noweibo
  github: http://github.com/ghw
  music: http://site.douban.com/linanya
  linkedin: https://www.linkedin.com/pub/nolinkkedin

# 站点信息
title: 我的互联网图书库！
description: My internet library!
url: http://bookcase.gehaowu.eu.org/bookcase/
rss_url: atom.xml

# gavatar头像及Favicon
gavatar: //dn-glibs.qbox.me/bookcase/img/deer3.png
favicon: //www.gehaowu.com/favicon.ico

# google analytics 设置
#ga:
#  id: UA-54262064-1 
#  url: painterlin.com

ba:
  id: 2f0f4b0d867163a00886350ad2c21f8c 

# disqus 设置
disqus:
  shortname: gehaowu

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: AboutMe
  newest: 最新文章
  archive: Archive